name: Make Module
on: 
  workflow_dispatch:
jobs:
  make_module:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 11
    - uses: nttld/setup-ndk@v1.2.0
      with:
        ndk-version: r21e
    - uses: gradle/gradle-build-action@v2
    - name: Make NDK
      run: ndk-build NDK_DEBUG=0
      working-directory: ./zygisk/module
    - name: Make Java
      run: bash gradlew assembleRelease
      working-directory: ./java
    - name: Make zip Module
      run: |
        version="$(grep '^version=' module.prop  | cut -d= -f2)"
        mkdir -p magisk/zygisk
        cp "../zygisk/module/libs/arm64-v8a/libsafetynetfix.so" "magisk/zygisk/arm64-v8a.so"
        cp "../zygisk/module/libs/armeabi-v7a/libsafetynetfix.so" "magisk/zygisk/armeabi-v7a.so"
        cp "../zygisk/module/libs/x86/libsafetynetfix.so" "magisk/zygisk/x86.so"
        cp "../zygisk/module/libs/x86_64/libsafetynetfix.so" "magisk/zygisk/x86_64.so"
        unzip "../java/app/build/outputs/apk/release/app-release.apk" "classes.dex"
        zip -r9 "../safetynet-fix-$version.zip" .
      working-directory: ./magisk
    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: Module
        path: ./safetynet-fix-*.zip

