name: Make release
on: 
    workflow_dispatch:
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Config
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'
    - uses: nttld/setup-ndk@v1.2.0
      with:
        ndk-version: r25b
    - uses: gradle/gradle-build-action@v2
