name: Run Gradle on PRs
on: 
  workflow_dispatch:
jobs:
  make_module:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 11
    - uses: nttld/setup-ndk@v1
      with:
        ndk-version: r25b
    - uses: gradle/gradle-build-action@v2
    - name: Make Java
      run: bash gradlew assembleRelease
      working-directory: ./java
    - name: Make NDK
      run: ndk-build NDK_DEBUG=0
      working-directory: ./zygisk/module
