name: Run Gradle on PRs
on: 
  workflow_dispatch:
jobs:
  make_java:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 11
    - uses: gradle/gradle-build-action@v2
    - working-directory: ./java
    - run: bash gradlew assembleRelease
